[build]
  # Comando para instalar dependencias de React, compilarlo y moverlo a /v2
  command = "npm run build"
  # Publicar el directorio actual (ra√≠z)
  publish = "."
  
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npx live-server ."
  port = 9000
  targetPort = 3000
  autoLaunch = true
